<?php

    $allCategories = [
        "Analog Synth",
        "Arpeggiator",
        "Bass",
        "Chorus",
        "Compressor",
        "Delay",
        "Distortion",
        "Drum Machine",
        "Dynamic EQ",
        "Effect",
        "EQ",
        "Filter",
        "Flanger",
        "Granular Synth",
        "Guitar",
        "Hardware Emulation",
        "Limiter",
        "Mastering",
        "MIDI",
        "Multi",
        "Utility",
        "Orchestral",
        "Percussion",
        "Phaser",
        "Piano",
        "Reverb",
        "Sampler",
        "Sequencer",
        "Soft Synth",
        "Sound Design",
        "String",
        "Surround",
        "Synth",
        "Vocal",
        "Wavetable Synth",
        "World",
        "Acoustic Drum",
        "Analog Drum",
        "Brass",
        "Cinematic",
        "Digital Drum",
        "FX",
        "Hip Hop",
        "House",
        "Jazz",
        "Metal",
        "Orchestra",
        "Pop",
        "Rock",
        "SFX",
        "Sound Effects",
        "Soundscapes",
        "Urban",
        "Vocals",
        "Woodwind",
        "World Percussion",
        "Other"
    ];
    ?>